export default [
  {
    name: "Kelechi Okoye",
    emailAddress: "kelechi.okoye10@example.com",
    password: "hashed_password_1",
    nationality: "nigeria",
    hiddenFields: ["emailAddress"],
    bio: "Pacy winger with a keen eye for goal. Former youth captain at Enyimba FC.",
    dob: new Date("1999-04-12"),
    physical: { height: "178cm", weight: "72kg", age: 25 },
    positions: ["forward", "striker"],
    socials: [
      { name: "Instagram", url: "https://instagram.com/kelechiokoye10" },
      { name: "Twitter", url: "https://twitter.com/okoyekelechi" },
    ],
    media: [
      {
        type: "video",
        url: "https://example.com/videos/okoye-highlight.mp4",
        description: "Highlight reel from 2024 season",
      },
    ],
    meta: { profileViews: 310 },
  },
  {
    name: "David Mensah",
    emailAddress: "d.mensah21@example.com",
    password: "hashed_password_2",
    nationality: "Ghana",
    bio: "Strong and tactical center-back. Ex-AshantiGold defender.",
    dob: new Date("1997-08-03"),
    physical: { height: "185cm", weight: "78kg", age: 27 },
    positions: ["defender"],
    socials: [{ name: "LinkedIn", url: "https://linkedin.com/in/davidmensah" }],
    media: [],
    meta: { profileViews: 120 },
  },
  {
    name: "Luka Petrovic",
    emailAddress: "luka.petro@example.com",
    password: "hashed_password_3",
    nationality: "Serbia",
    hiddenFields: ["physical.age"],
    bio: "Calm presence between the sticks. Reliable shot-stopper.",
    dob: new Date("1995-01-17"),
    physical: { height: "190cm", weight: "82kg", age: 29 },
    positions: ["goalkeeper"],
    socials: [],
    media: [
      {
        type: "image",
        url: "https://example.com/images/luka-dive.jpg",
        description: "Spectacular save vs rivals",
      },
    ],
    meta: { profileViews: 92 },
  },
  {
    name: "Samuel Obinna",
    emailAddress: "obinna.samuel23@example.com",
    password: "hashed_password_4",
    nationality: "Nigeria",
    bio: "Dynamic attacking midfielder, strong passer and creative mind.",
    dob: new Date("2000-05-22"),
    physical: { height: "174cm", weight: "68kg", age: 24 },
    positions: ["midfielder"],
    socials: [{ name: "Instagram", url: "https://instagram.com/samuelobinna" }],
    media: [],
    meta: { profileViews: 225 },
  },
  {
    name: "Miguel Sanchez",
    emailAddress: "miguel.s@futbolmail.com",
    password: "hashed_password_5",
    nationality: "Mexico",
    bio: "Fast winger with an eye for crosses. Liga MX academy product.",
    dob: new Date("2001-03-14"),
    physical: { height: "172cm", weight: "66kg", age: 23 },
    positions: ["forward"],
    socials: [],
    media: [],
    meta: { profileViews: 156 },
  },
  {
    name: "Julian Meier",
    emailAddress: "julian.meier@example.de",
    password: "hashed_password_6",
    nationality: "Germany",
    bio: "Versatile midfielder, excels in both attack and defense.",
    dob: new Date("1998-09-01"),
    physical: { height: "180cm", weight: "75kg", age: 26 },
    positions: ["midfielder"],
    socials: [{ name: "Twitter", url: "https://twitter.com/julianmeier8" }],
    media: [],
    meta: { profileViews: 88 },
  },
  {
    name: "Thierry Diop",
    emailAddress: "t.diop.senegal@example.com",
    password: "hashed_password_7",
    nationality: "Senegal",
    bio: "Commanding defender, great aerial presence. Former U20 national player.",
    dob: new Date("1996-11-09"),
    physical: { height: "188cm", weight: "80kg", age: 28 },
    positions: ["defender"],
    socials: [],
    media: [],
    meta: { profileViews: 190 },
  },
  {
    name: "Aaron Smith",
    emailAddress: "a.smith123@example.com",
    password: "hashed_password_8",
    nationality: "England",
    bio: "Midfielder with high work rate and long-range passing.",
    dob: new Date("1999-02-26"),
    physical: { height: "181cm", weight: "76kg", age: 25 },
    positions: ["midfielder"],
    socials: [],
    media: [],
    meta: { profileViews: 300 },
  },
  {
    name: "Carlos Junior",
    emailAddress: "carlosjr@example.com",
    password: "hashed_password_9",
    nationality: "Brazil",
    bio: "Left-footed striker with a powerful shot. Copa Sao Paulo standout.",
    dob: new Date("2002-12-02"),
    physical: { height: "177cm", weight: "70kg", age: 22 },
    positions: ["striker"],
    socials: [{ name: "YouTube", url: "https://youtube.com/carlosgoals" }],
    media: [],
    meta: { profileViews: 430 },
  },
  {
    name: "Yusuf Abubakar",
    emailAddress: "yusuf.abubakar@example.ng",
    password: "hashed_password_10",
    nationality: "Nigeria",
    bio: "Hard-tackling defensive midfielder with great stamina.",
    dob: new Date("1997-06-30"),
    physical: { height: "179cm", weight: "74kg", age: 27 },
    positions: ["midfielder"],
    socials: [],
    media: [],
    meta: { profileViews: 210 },
  },
];
